"""empty message

Revision ID: 59d854e77d9f
Revises: d2b48d7e4ad0
Create Date: 2018-10-12 22:18:40.350129

"""
import sqlite3
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '59d854e77d9f'
down_revision = 'd2b48d7e4ad0'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    # https://datasette.readthedocs.io/en/stable/spatialite.html
    if conn.dialect.name == 'sqlite':
        conn.execute(text('SELECT InitSpatialMetadata(1)'))

        conn.execute(text(
            """
            SELECT AddGeometryColumn('user', 'location', 4326, 'POINT', 2);
            """))
        # Add a spatial index against the new column
        conn.execute(text(
            """
            SELECT CreateSpatialIndex('user', 'location');
            """))
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('user', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', management=True), nullable=True))
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
